  version: '3'
  services:
    backend:
      build: 
        context : logeshc12/cocoloco-ecommerce-backend
      ports :
        - '3000:3000'
      networks:
        - mern-network
      
      
      

    mongodb:
      image: mongo:latest
      ports:
        - '27017:27017'      # Expose MongoDB if needed for external access
      networks:
        - mern-network
      volumes:
        - mongo-data:/data/db         # Persistent storage for MongoDB data



# here i will create a mern -network

  networks:
    mern-network:
      driver: bridge

  volumes:
    mongo-data:
      driver: local 